import { test, expect } from '@playwright/test';
import type { Page } from '@playwright/test';
import { requestMagicLink, readMagicLinkUrl, getSession } from './helpers/auth';

// Story A2 — the public front door at `/`.
//
// `/` is the one page a signed-out visitor can reach (route protection is
// A3). It shows the app, an email field that requests a magic link, a
// "check your email" confirmation once the link is issued, and a quiet line
// about the address not being shared or spammed. A visitor who is already
// signed in is sent on to /puzzles.
//
// This spec asserts structure and behaviour, not marketing prose — the copy
// is described in the story doc and free to change; the testids, the sent
// state, and the redirect are the contract. It reuses e2e/helpers/auth.ts
// (from A1) for the already-signed-in case. Do not edit this file to match
// an implementation.

function uniqueEmail(label: string) {
  return `a2-${label}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}@example.test`;
}

async function waitForFrontDoorReady(page: Page): Promise<void> {
  // The submit handler isn't live until hydration commits — same race the
  // rest of the suite guards with data-ready (see helpers/wait-for-ready.ts).
  await page.waitForSelector('[data-testid="sign-in-form"][data-ready="true"]');
}

test.describe('A2 — the front door', () => {
  test('is public and shows the sign-in form to a signed-out visitor', async ({
    page,
  }) => {
    await page.goto('/');

    // Not redirected: a signed-out visitor stays on `/`.
    await expect(page).toHaveURL(/\/$/);

    await expect(page.getByTestId('front-door')).toBeVisible();
    await expect(page.getByTestId('sign-in-email')).toBeVisible();
    await expect(page.getByTestId('sign-in-submit')).toBeVisible();
    await expect(page.getByTestId('sign-in-privacy')).toBeVisible();
  });

  test('requesting a link shows the sent state and actually issues a link', async ({
    page,
  }) => {
    const email = uniqueEmail('request');
    await page.goto('/');
    await waitForFrontDoorReady(page);

    await page.getByTestId('sign-in-email').fill(email);
    await page.getByTestId('sign-in-submit').click();

    // The visible confirmation the epic requires.
    await expect(page.getByTestId('sign-in-sent')).toBeVisible();

    // And a real link was issued: the sent state is shown only after the
    // request succeeds, so by now the token is in the database. Reading it
    // ties the UI action to a backend effect — this can't pass on a state
    // toggle alone.
    expect(await readMagicLinkUrl(email)).toBeTruthy();
  });

  test('a signed-in visitor at / is redirected to /puzzles', async ({ page }) => {
    const email = uniqueEmail('redirect');

    // Sign in through the A1 flow, then come back to `/`.
    await requestMagicLink(page, email);
    await page.goto(await readMagicLinkUrl(email));
    expect((await getSession(page))?.user?.email).toBe(email);

    await page.goto('/');
    await expect(page).toHaveURL(/\/puzzles(\/|$|\?)/);
  });
});
