import { test, expect } from '@playwright/test';
import {
  requestMagicLink,
  readMagicLinkUrl,
  getSession,
  signOut,
} from './helpers/auth';

// Story A1 — the magic-link flow, driven end to end with no inbox.
//
// A person supplies an email, a link is issued, they click it, and their
// browser is now signed in; signing out reverses it. The link is read from
// the database rather than an email — the epic's "tests never send email"
// rule (docs/epics/09-accounts-epic.md).
//
// Nothing is protected yet (route protection is A3), so "signed in" is
// proven by Better Auth's own session reflecting the user, not by reaching a
// gated page.
//
// This file is the frozen specification: it asserts behaviour only. Every
// Better-Auth-specific detail — endpoint paths, where the token is stored,
// how the session is read — lives in ./helpers/auth.ts, which is ordinary
// plumbing the implementer owns and adjusts to the installed version. Do not
// move that wiring into this file, and do not edit this file to match an
// implementation.

function uniqueEmail(label: string) {
  return `a1-${label}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}@example.test`;
}

test.describe('A1 — magic-link sign-in', () => {
  test('a fresh email requests a link, follows it, and ends up signed in', async ({
    page,
  }) => {
    const email = uniqueEmail('signin');

    await requestMagicLink(page, email);

    // Read straight from the database, never an inbox.
    const url = await readMagicLinkUrl(email);
    expect(url, 'a magic link was issued and stored').toBeTruthy();

    // Follow it the way a person clicking their email would.
    await page.goto(url);

    const session = await getSession(page);
    expect(session?.user?.email).toBe(email);
  });

  test('signing out clears the session', async ({ page }) => {
    const email = uniqueEmail('signout');

    await requestMagicLink(page, email);
    await page.goto(await readMagicLinkUrl(email));
    expect((await getSession(page))?.user?.email).toBe(email);

    await signOut(page);

    expect(await getSession(page)).toBeNull();
  });
});
